import { encode } from "@toon-format/toon";
import type { Questionnaire } from "../schema/answer-lawsuit";
const getCurrentDate = () => {
  return new Date().toISOString().split("T")[0]; // Returns YYYY-MM-DD
};

export function getFdcpaPrompt({ context }: { context: string }) {
  return `
        You are an FDCPA (Fair Debt Collection Practices Act) violation detection system.

        Analyze this debt collection letter and identify any violations of 15 U.S.C. §1692.

        LETTER TEXT:
        ${context}

        Scan for these specific violations:
        1. Threats of illegal action (arrest, jail, wage garnishment without court order)
        2. False statements about debt amount or legal status
        3. Harassment, abuse, or profane language
        4. Contact outside 8am-9pm
        5. Contacting employer
        6. Disclosing debt to third parties
        7. Missing Mini-Miranda warning ("This is an attempt to collect a debt...")
        8. Continuing contact after cease & desist
        9. False representation of being attorney/government
        10. Threatening to report to credit bureaus falsely

        For each violation found, provide:
        - Violation type
        - Specific FDCPA section violated (e.g., §1692d, §1692e, §1692f)
        - Quote from letter showing violation
        - Confidence score (0-100%)
        - Explanation

        Output as JSON array. The date is ${getCurrentDate()}.
    `;
}

export function coverLetterPrompt(violations: any, context: string) {
  return `
        Generate a professional FDCPA violation demand letter.

VIOLATIONS DETECTED:
${JSON.stringify(violations, null, 2)}

Other Context: 
${context}


Generate a demand letter with:
1. Professional business letter format
2. Date and addresses
3. RE: line with case reference
4. Clear statement of each violation with statutory citation
5. Demand for:
   - Immediate cease of collection activities
   - Written validation of debt
   - Statutory damages ($1,000 per violation under §1692k)
   - Actual damages (emotional distress)
6. 15-day response deadline
7. Warning of potential legal action

Tone: Assertive but professional (not threatening)

Output the complete letter ready to send.
    `;
}

export function extractAllegationsPrompt({ context }: { context: string }) {
  return `
        Extract the allegations from the following text.

        TEXT:
        ${context}

      "allegations":[
      {"id":1,"text":"Defendant owes $4,500 on account 12345."},
      {"id":2,"text":"Last payment on 2019-01-15."},
      {"id":3,"text":"Plaintiff claims ownership of the account."}
    ],

        Output the allegations as a JSON array.
    `;
}

export function extractViolationsPrompt({ context }: { context: string }) {
  // prompt generated by llm - claude sonnet 4.5
  return `
    You are an expert consumer protection attorney specializing in the Fair Debt Collection Practices Act (FDCPA). Analyze the debt collection letter below and identify all FDCPA violations.

    Today's date is ${new Date().toISOString().split("T")[0]}.

    ## Check for These Violations:

  1. **Threats of Illegal Action** (§ 1692e(4)(5)) - Threats that can't legally be taken
  2. **False Statements** (§ 1692e) - Misrepresented debt amount, creditor, or consequences  
  3. **Harassment** (§ 1692d) - Threatening/obscene language, excessive contact
  4. **Time Violations** (§ 1692c(a)(1)) - Contact before 8am or after 9pm
  5. **Third-Party Contact** (§ 1692c) - Contacting employer or disclosing debt to others
  6. **Cease & Desist Violations** (§ 1692c(c)) - Contact after written cease request
  7. **Mini-Miranda Missing** (§ 1692e(11)) - Missing "This is an attempt to collect a debt..." disclosure
  8. **Validation Notice Missing** (§ 1692g) - Missing debt amount, creditor name, 30-day validation period, or dispute rights
  9. **False Urgency** (§ 1692e(10)) - Fake deadlines or "act now" pressure
  10. **Unfair Practices** (§ 1692f) - Unauthorized fees or charges

## Output Format:

**VIOLATIONS FOUND:**
For each violation, provide:
- FDCPA Section violated
- Exact quote from letter as evidence
- Brief explanation
- Confidence (High/Medium/Low)

**VALIDATION ELEMENTS:**
- Debt amount stated? Original creditor named? 30-day period disclosed? Dispute rights explained?

**RECOMMENDATIONS:**
- Statutory damages estimate
- Key demands (cease contact, debt validation, compensation)

Be precise. Quote exact text. Only flag clear violations.

---

**Analyze this letter:**

${context}
  `;
}

export function generateLetterPrompt({
  violations,
  context,
}: {
  violations: {
    fdcpaSection: string;
    quote: string;
    explanation: string;
    confidence: string;
  }[];
  context: string;
}) {
  return `
    You are an expert consumer protection attorney drafting a professional demand letter for FDCPA violations. Generate a formal, legally sound demand letter based on the violations identified.

    ## Letter Requirements:

    - Professional, firm tone without being aggressive
    - Cite specific FDCPA sections violated
    - Reference exact quotes from the original letter as evidence
    - Clearly state all demands
    - Include legal consequences for non-compliance
    - Set a 30-day response deadline

    ## Letter Structure:

    **[Consumer Name and Address]**
    **[Date]**

**[Debt Collector Name and Address]**

**RE: FDCPA Violations - Account #[Number] - Formal Demand for Cessation and Compensation**

**Dear [Collector Name],**

[Opening paragraph: State purpose - responding to their letter dated X, identifying multiple FDCPA violations]

**Violations Identified:**

[For each violation: State the violation type, cite the FDCPA section, quote their exact language, explain why it violates the law]

**Formal Demands:**

1. Immediate cessation of all collection activities
2. Written validation of the alleged debt within 30 days including:
   - Original signed contract or agreement
   - Complete payment history
   - Proof of your authority to collect
3. Compensation for statutory damages under 15 U.S.C. § 1692k ($[amount])
4. Removal of any negative credit reporting related to this account
5. Written confirmation of compliance with these demands

**Legal Notice:**

[State consequences: right to sue within one year, attorney fees and costs recoverable, potential additional damages]

This letter serves as formal notice under 15 U.S.C. § 1692c(c) to cease all further communication except to confirm compliance or notify of specific legal action.

You have 30 days from receipt to respond in writing. Failure to comply will result in formal legal action.

**Sincerely,**

**[Consumer Name]**

---

## Input Data:


**ORIGINAL LETTER TEXT:**
${context}

**VIOLATIONS IDENTIFIED:**
${JSON.stringify(violations, null, 2)}


---

Generate the complete demand letter now.
  `;
}

export function generateDraftPrompt({
  allegations,
  questionnaire,
  pdf_content,
}: {
  allegations: {
    id: number;
    text: string;
  }[];
  questionnaire: Questionnaire;
  pdf_content: string;
}) {
  const encodedAllegations = encode(allegations);
  const encodedPdfContent = encode(pdf_content);
  return `You are a legal document assistant. Generate a complete Answer to a civil lawsuit complaint in markdown format.
        Important notes:
-  All responses in the Answer document must refer to the "  Defendant" in the third person 
(e.g., "Defendant denies", "Defendant asserts", "Defendant lacks knowledge"). 
Do NOT use "I" or "me" except inside the Certificate of Service section.
IMPORTANT OUTPUT FORMAT:
- Return ONLY plain markdown text content
- Do NOT wrap the output in code blocks (no \`\`\`markdown or \`\`\`)
- Do NOT include file extensions or format indicators
- Return the markdown content directly as a string
- Use standard markdown syntax for formatting (headers, lists, bold, etc.)

COMPLAINT ALLEGATIONS:
${encodedAllegations}

CASE INFORMATION:
- State: ${questionnaire.state}
- County: ${questionnaire.county}
- Court: ${questionnaire.courtName}
- Case Number: ${questionnaire.caseNumber}

DEBT INFORMATION:
- Amount Claimed: $${questionnaire.debtAmount || "Not specified"}
- Do you owe this debt?: ${questionnaire.oweDebt}
- Last Payment Date: ${questionnaire.lastPaymentDate || "Not specified"}
- Properly Served?: ${questionnaire.properlyServed}

FDCPA VIOLATIONS (if applicable):
${
  Object.entries(questionnaire.fdcpaViolations)
    .filter(([_, value]) => value)
    .map(([key]) => `- ${key.replace(/([A-Z])/g, " $1").trim()}`)
    .join("\n") || "None reported"
}

ORIGINAL COMPLAINT TEXT:
${encodedPdfContent.substring(0, 2000)}${
    encodedPdfContent.length > 2000 ? "..." : ""
  }

INSTRUCTIONS:
Generate a complete Answer document in markdown format that includes:

1. CASE CAPTION (at the top):
   - Court name
   - Case number
   - Plaintiff vs Defendant
   - State and county

2. RESPONSES TO ALLEGATIONS:
   For each allegation numbered ${allegations
     .map((a) => a.id)
     .join(", ")}, respond with:
   - "ADMITS" if true
   - "DENIES" if false
   - "LACKS SUFFICIENT KNOWLEDGE" if uncertain
   Format as: "Allegation [number]: [response]"

3. AFFIRMATIVE DEFENSES:
   Include relevant defenses such as:
   - Statute of limitations (if applicable)
   - Lack of standing
   - Amount in dispute
   - FDCPA violations (if any were checked)
   - Improper service (if not properly served)
   - Failure to state a claim

4. SIGNATURE BLOCK:
   - Pro se format
   - Date
   - Signature line

5. CERTIFICATE OF SERVICE (if required by state):
   - Statement of service method
   - Date of service

OUTPUT: Return the complete Answer document as plain markdown text. Do not wrap in code blocks or add any file format indicators
.`;
}
